### ISSUE TITLE
Stuck at Pemasangan Berjaya page

### ISSUE THREAD

**Issue by a-fauzi-s** [seajell/seajell#105]
**Describe the bug**
Log Masuk button not redirect to the log masuk page instead stuck at the same page

**Screenshots**
[https://www.awesomescreenshot.com/video/6404863?key=b1cb45ac6d9f3520d76e2f4eaea2c9b4] (url)

**Desktop (please complete the following information):**
 - Browser [Microsoft Edge]
 - Version [96.0.1054.43]

**Comment by hanisirfan** [comment]
May I know the branch of this code? Is it the `main` branch?

Can you inspect element the button and send the screenshot here?

Thanks,

**Comment by hanisirfan** [comment]
Oh just a note for you, the main UI for this project is currently in Malay language. I'm in the process of translating it into English and will be released in version 2. You can check the current progress from the [translation_works](https://github.com/seajell/seajell/tree/translation_works) branch.

**Comment by a-fauzi-s** [comment]
Yes the branch code tht i downloaded is main branch

Here is the inspect screenshot:
![image](https://user-images.githubusercontent.com/76209562/145779823-3cd01972-f862-4c5b-be4c-c18f2f170891.png)

**Comment by hanisirfan** [comment]
Oh I know why. You haven't compiled the assets yet. You can follow the proper installation steps [here](https://docs.seajell.xyz/en/latest/installation/#source-code-for-developers). Compiled binary for version 2 will be released when it's done.
