### ISSUE TITLE
Change URL In Main Website and Documentation

### ISSUE THREAD

**Issue by hanisirfan** [seajell/seajell#74]
Change the URL for GitHub repo to https://github.com/seajell/seajell and documentation website to https://docs.seajell.xyz

**Comment by hanisirfan** [comment]
Also change the URL in the documentation website.

**Comment by Adi7171** [comment]
I would like to contribute to this issue for Hacktoberfest.

**Comment by hanisirfan** [comment]
No problem. But I think it's better for you to wait until 1 October and you have signed up for Hacktoberfest. I believe, any PR before that will be ignored.
